# Generated by Django 2.2 on 2020-05-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
    ]
