# Generated by Django 2.2 on 2020-05-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200510_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='duration',
            field=models.CharField(default=None, max_length=6),
            preserve_default=False,
        ),
    ]
