# Generated by Django 2.2 on 2020-05-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20200512_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='mealType',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
