# Generated by Django 2.2 on 2020-05-14 13:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_mealtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingNote',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='tools',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=None, size=None),
            preserve_default=False,
        ),
    ]
