# Generated by Django 2.2 on 2020-05-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20200514_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='note',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
